# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      # Runs a set of commands using the runners shell
      - name: Set env_var and Build
        run: |
          export NODE_ENV=gh-pages
          npm install @vue/cli
          npm install
          vue add pwa
          npm run build
      - name: Publish to gh-pages
        run: |
          REPOSITORY_NAME="${GITHUB_REPOSITORY}"
          DEPLOY_REPO="https://${{ secrets.ACCESS_TOKEN }}@github.com/${REPOSITORY_NAME}.git"
          cd dist
          git init
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m 'Auto deploy'
          git push --force $DEPLOY_REPO master:gh-pages
          rm -fr .git
          
